---
- name: Enable netconf 
  hosts: vsrx
  connection: ansible.netcommon.network_cli
  gather_facts: no

  tasks:
          - name: Enable netconf
            junipernetworks.junos.junos_netconf:
                    netconf_port: 830
                    state: present
